config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord

  #Class Method
  def self.by_first_name
    order(:first_name)
  end  

  #Instance Method 
  def full_name
    return "#{self.first_name} #{self.last_name}"
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
  @people = Person.all
  end
  
  def show
  @person = Person.find(params[:id])
  end
  
  def new
  @person = Person.new
  end  
  
  def create
  @person = Person.new(person_params)
  
  if @person.save
  redirect_to people_path
  else 
  render :new
  end
  end
  
  def edit
  @person = Person.find(params[:id])
  end
  
  def update
  @person = Person.find(params[:id])
  if @person.update(person_params)
  redirect_to people_path
  else 
  render :edit  
  end 
  end  
  
  def destroy
  Person.find(params[:id]).destroy
  redirect_to people_path
  end  
  
  private
  
  def person_params
  params.require(:person,).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender, :alive)
  end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', people_path %>
<%= link_to 'Show', people_path %>
<%= link_to 'People', people_path %>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1> Edit Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :age %>
  <%= f.text_area :age %>

  <%= f.label :hair_color %>
  <%= f.text_area :hair_color %>

  <%= f.label :eye_color%>
  <%= f.text_area :eye_color%>

  <%= f.label :gender %>
  <%= f.text_area :gender %>

  <%= f.label :alive %>
  <%= f.text_area :alive %>

  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1>Person</h1>
<p><%= link_to "New Person", new_person_path %></p>

<% @people.each do |person| %>
  <h2> <%= person.full_name%> </h2>
  <%= link_to "Show Person", person_path(person.id) %>
  <%= link_to "Edit Person", edit_person_path(person.id) %>
  <%= link_to "Delete Person", person_path(person.id), method: :delete  %>
  <% end %>

app/views/people/new.html.erb
<h1> Edit Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :age %>
  <%= f.text_area :age %>

  <%= f.label :hair_color %>
  <%= f.text_area :hair_color %>

  <%= f.label :eye_color%>
  <%= f.text_area :eye_color%>

  <%= f.label :gender %>
  <%= f.text_area :gender %>

  <%= f.label :alive %>
  <%= f.text_area :alive %>

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1><%= @person.first_name %></h1>
<h1><%= @person.last_name %></h1>
<h2><%= @person.age %></h2>
<h3><%= @person.hair_color %></h3>
<h3><%= @person.eye_color %></h3>
<h3><%= @person.gender %></h3>
<h4><%= @person.alive %></h4>

<%= link_to 'Back', person_path %>